version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 BelTube.wsgi:application
    environment:
      - DATABASE_HOST=db        
      - DATABASE_NAME=beltube_db     
      - DATABASE_USER=admin_beltube
      - DATABASE_PASSWORD=518666
    volumes:
      - .:/app
      - static_volume:/app/staticfiles 
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
    ports:
      - "6379:6379"


  db:
    image: postgres:17
    environment:
      POSTGRES_DB: beltube_db
      POSTGRES_USER: admin_beltube
      POSTGRES_PASSWORD: 518666
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - static_volume:/app/staticfiles:ro  # Только чтение для Nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./media:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:



  